package main

import (
	"fmt"
	// "github.com/yuya373/concurrency/chapter3"
	"github.com/yuya373/concurrency/chapter4"
)

func main() {
	fmt.Println("https://www.oreilly.co.jp/books/9784873118468/")
	// chapter3.Cond()
	// chapter3.Broadcast()
	// chapter3.Once()
	// chapter3.Pitfall()
	// chapter3.Deadlock()
	// chapter3.Pool()
	// chapter3.MemPool()
	// chapter3.UniDirectionalChan()
	// chapter3.ClosedChan()
	// chapter3.HandleChannelWithLoop()
	// chapter3.NotifyChannelWithClose()
	// chapter3.BufferedChan()
	// chapter3.NilChannel()
	// chapter3.OwnerAndConsumer()
	// chapter3.Select()
	// chapter3.SelectMultiple()
	// chapter3.SelectTimeout()
	// chapter3.SelectDefault()
	// chapter3.SelectBreak()
	// chapter4.AdhocBind()
	// chapter4.LexicalBind()
	// chapter4.SimpleLeak()
	// chapter4.FixSimpleLeak()
	// chapter4.SendLeak()
	// chapter4.FixSendLeak()
	// chapter4.Or()
	// chapter4.PrintError()
	// chapter4.HandleError()
	// chapter4.BasicPipeline()
	// chapter4.ChannelPipeline()
	// chapter4.Repeat()
	// chapter4.RepeatFn()
	// chapter4.NaivePrimeFinder()
	// chapter4.FanOutFanInPrimeFinder()
	// chapter4.OrDone()
	// chapter4.Tee()
	// chapter4.Bridge()
	// chapter4.GreetingAndFarewell()
	// chapter4.GreetingAndFarewellWithContext()
	// chapter4.DataBag()
	// chapter4.SafeMapKey()
	chapter4.SafeDataBag()
}
